name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test Installation
        run: |
          brew install --build-from-source ./boogiewoogie.rb
          boogiewoogie version

      - name: Run Basic Tests
        run: |
          boogiewoogie help
          mkdir -p ~/.boogiewoogie
          touch ~/.boogiewoogie/profiles.conf